### ISSUE TITLE
Access to the bin/ directory

### ISSUE THREAD

**Issue by LuanHimmlisch** [linuxserver/docker-grav#12]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Desired Behavior

There should be a volume to get access to the Grav CMS `bin/` directory, since certain vital CLI plugins such as devtools are accesed from there.

## Current Behavior

You don't have access to the `bin/` directory.

## Alternatives Considered

Haven't found a way to access the folder.

**Comment by thespad** [comment]
Please see https://github.com/linuxserver/docker-grav/pull/13 - information about accessing the CLI tools has been added to the readme.
