### ISSUE TITLE
GRAV_ENVIRONMENT not honored

### ISSUE THREAD

**Issue by psy0rz** [linuxserver/docker-grav#16]
As per documentation, this variable is used for multi site setup: https://learn.getgrav.org/17/advanced/multisite-setup

Since its probably filtered somewhere, grav will fall back to the default environment which is based on the visited domain. This has unintended consquences.

**Comment by psy0rz** [comment]
I fiddled around a bit: First you have to set S6_KEEP_ENV=1 via docker.

Then you need to adjust both php.ini and the www php-fpm config file to allow environment variables. Maybe there's an official way for it?

**Comment by thespad** [comment]
Allowing PHP to retain envs isn't too difficult a change, we can certainly look to do it. S6_KEEP_ENV shouldn't be required as the nginx service is run with contenv which passes the container environment to it.

**Comment by psy0rz** [comment]
No, php needs the environment variables, not nginx?

**Comment by aptalca** [comment]
php is also run with contenv so it has access to the vars

But like spad said, php by default ignores the system env vars. There is a flag you need to add to the php-local.ini so it doesn't ignore them

**Comment by psy0rz** [comment]
Could you perhaps add an option for that as well?

**Comment by thespad** [comment]
Can you please test with `lspipepr/grav:1.7.35-pkg-9023161a-pr-18` and see if it works as desired.

**Comment by psy0rz** [comment]
uuh..whats the full image-url i put in my compose file?

**Comment by j0nnymoe** [comment]
That is the image repo/name.

**Comment by psy0rz** [comment]
thanks, that works! grav/php now sees the variable.

I'm not sure when grav decides to create an actual environment. (on my production server it does, somehow, and on my test it never does) But thats a grav-thing, so i'll figure that out.

Thanks!

**Comment by thespad** [comment]
PR is merged so once it's built in ~30 minutes you can switch back to the "normal" image again.

**Comment by psy0rz** [comment]
very nice, i love linuxserver images :)
