### ISSUE TITLE
Grav Could not resolve multiple adresses 

### ISSUE THREAD

**Issue by DennisYildirim** [linuxserver/docker-grav#17]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Steps to Reproduce

1. Create the docker container by using portainer with this stack: 

version: "2.1"
services:
  grav:
    image: lscr.io/linuxserver/grav:latest
    container_name: grav

    environment:
      # for GroupID
      - PUID=${PUID:-1026}
      # for UserID
      - PGID=${PGID:-100}
      # Specify a timezone to use for example Europe/Amsterdam
      - TZ=${TZ:-Australia/Melbourne}
    volumes:
      - ${BASEDIR:-/volume1/docker}/grav/config:/config
    ports:
      - 85:80
    restart: unless-stopped

3. Give it sometime to settle.
4. Login to grav by using the port 85. Set up the admin credentials. 
5. Bam : starts giving the errors i pasted. 

## Environment
**OS:** : Synology DS1821+
**CPU architecture:** not sure
**How docker service was installed:**

## Command used to create docker container (run/create/compose/screenshot)

![image](https://user-images.githubusercontent.com/81414162/188294129-ad3bca29-825b-4aca-88c7-c8877b9accdd.png)
![image](https://user-images.githubusercontent.com/81414162/188294141-df3d4e47-b4a7-4c4f-9e50-5ca99083d4bc.png)
![image](https://user-images.githubusercontent.com/81414162/188294146-e6ddd57c-244a-4ed6-833f-b45a29072d6b.png)

## Docker logs

Inspect Log: 

07f4c730b640b9032d9b728a8d1fafa1f32dbc9cb497945768dc68c37c448fb1
AppArmorProfile docker-default
Args [ ]
Config { AttachStderr: true, AttachStdin: false, AttachStdout: true, Cmd: null, DDSM: false, Domainname: , Entrypoint: /init, Env: PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin,PS1=$(whoami)@$(hostname):$(pwd)\$ ,HOME=/root,TERM=xterm,S6_CMD_WAIT_FOR_SERVICES_MAXTIME=0,PGID=100,TZ=Australia/Melbourne,PUID=1026, ExposedPorts: [object Object], Hostname: 07f4c730b640, Image: lscr.io/linuxserver/grav:latest, Labels: [object Object], OnBuild: null, OpenStdin: false, StdinOnce: false, Tty: false, User: , Volumes: [object Object], WorkingDir: }
Created 2022-09-04T01:51:25.628991215Z
Driver btrfs
ExecIDs
GraphDriver { Data: null, Name: btrfs }
HostConfig { AutoRemove: false, Binds: /volume1/docker/grav/config:/config:rw, BlkioDeviceReadBps: null, BlkioDeviceReadIOps: null, BlkioDeviceWriteBps: null, BlkioDeviceWriteIOps: null, BlkioWeight: 0, BlkioWeightDevice: null, CapAdd: null, CapDrop: null, Cgroup: , CgroupParent: , CgroupnsMode: host, ConsoleSize: 0,0, ContainerIDFile: , CpuCount: 0, CpuPercent: 0, CpuPeriod: 0, CpuQuota: 0, CpuRealtimePeriod: 0, CpuRealtimeRuntime: 0, CpuShares: 0, CpusetCpus: , CpusetMems: , DeviceCgroupRules: null, DeviceRequests: null, Devices: null, Dns: null, DnsOptions: null, DnsSearch: null, Env: PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin,PS1=$(whoami)@$(hostname):$(pwd)\$ ,HOME=/root,TERM=xterm,S6_CMD_WAIT_FOR_SERVICES_MAXTIME=0,PGID=100,TZ=Australia/Melbourne,PUID=1026, ExtraHosts: , GroupAdd: null, IOMaximumBandwidth: 0, IOMaximumIOps: 0, IpcMode: private, Isolation: , KernelMemory: 0, KernelMemoryTCP: 0, Links: null, LogConfig: [object Object], MaskedPaths: /proc/asound,/proc/acpi,/proc/kcore,/proc/keys,/proc/latency_stats,/proc/timer_list,/proc/timer_stats,/proc/sched_debug,/proc/scsi,/sys/firmware, Memory: 0, MemoryReservation: 0, MemorySwap: 0, MemorySwappiness: null, NanoCpus: 0, NetworkMode: grav_default, OomKillDisable: false, OomScoreAdj: 0, PidMode: , PidsLimit: null, PortBindings: [object Object], Privileged: false, PublishAllPorts: false, ReadonlyPaths: /proc/bus,/proc/fs,/proc/irq,/proc/sys,/proc/sysrq-trigger, ReadonlyRootfs: false, RestartPolicy: [object Object], Runtime: runc, SecurityOpt: null, ShmSize: 67108864, UTSMode: , Ulimits: null, UsernsMode: , VolumeDriver: , VolumesFrom: null }
HostnamePath /volume1/@docker/containers/07f4c730b640b9032d9b728a8d1fafa1f32dbc9cb497945768dc68c37c448fb1/hostname
HostsPath /volume1/@docker/containers/07f4c730b640b9032d9b728a8d1fafa1f32dbc9cb497945768dc68c37c448fb1/hosts
Id 07f4c730b640b9032d9b728a8d1fafa1f32dbc9cb497945768dc68c37c448fb1
Image sha256:2fe0a61267d05ce3e70aacd3936950c34f844af99ac0b7a26e11dc5f7d9ae7db
LogPath /volume1/@docker/containers/07f4c730b640b9032d9b728a8d1fafa1f32dbc9cb497945768dc68c37c448fb1/log.db
MountLabel
Mounts [ [object Object] ]
Name /grav
NetworkSettings { Bridge: , EndpointID: , Gateway: , GlobalIPv6Address: , GlobalIPv6PrefixLen: 0, HairpinMode: false, IPAddress: , IPPrefixLen: 0, IPv6Gateway: , LinkLocalIPv6Address: , LinkLocalIPv6PrefixLen: 0, MacAddress: , Networks: [object Object], Ports: [object Object], SandboxID: 02d3a1851153a2bdcb05bd9c0d56cfa91b03c5180e123144b28cebe58c557c8a, SandboxKey: /var/run/docker/netns/02d3a1851153, SecondaryIPAddresses: null, SecondaryIPv6Addresses: null }
Path /init
Platform linux
Portainer { ResourceControl: [object Object] }
ProcessLabel
ResolvConfPath /volume1/@docker/containers/07f4c730b640b9032d9b728a8d1fafa1f32dbc9cb497945768dc68c37c448fb1/resolv.conf
RestartCount 0
State { Dead: false, Error: , ExitCode: 0, FinishedAt: 0001-01-01T00:00:00Z, FinishedTs: -62135596800, OOMKilled: false, Paused: false, Pid: 30835, Restarting: false, Running: true, StartedAt: 2022-09-04T01:51:54.036348683Z, StartedTs: 1662256314, Status: running }

**Comment by DennisYildirim** [comment]
Sorry : adding the docker log, somehow markdown does not show it. I'm new in submitting bugs :) 
```
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service 00-legacy: starting
s6-rc: info: service 00-legacy successfully started
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
cont-init: info: running /etc/cont-init.d/01-envfile
cont-init: info: /etc/cont-init.d/01-envfile exited 0
cont-init: info: running /etc/cont-init.d/01-migrations
[migrations] started
[migrations] 01-nginx-site-confs-default: skipped
[migrations] 02-default-location: skipped
[migrations] done
cont-init: info: /etc/cont-init.d/01-migrations exited 0
cont-init: info: running /etc/cont-init.d/02-tamper-check
cont-init: info: /etc/cont-init.d/02-tamper-check exited 0
cont-init: info: running /etc/cont-init.d/10-adduser

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/


Brought to you by linuxserver.io
-------------------------------------

To support the app dev(s) visit:
Grav: https://opencollective.com/grav/donate

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    1026
cont-init: info: /etc/cont-init.d/10-adduser exited 0
cont-init: info: running /etc/cont-init.d/11-folders
cont-init: info: /etc/cont-init.d/11-folders exited 0
cont-init: info: running /etc/cont-init.d/12-samples
cont-init: info: /etc/cont-init.d/12-samples exited 0
cont-init: info: running /etc/cont-init.d/13-nginx
cont-init: info: /etc/cont-init.d/13-nginx exited 0
cont-init: info: running /etc/cont-init.d/14-php
cont-init: info: /etc/cont-init.d/14-php exited 0
cont-init: info: running /etc/cont-init.d/15-keygen
cont-init: info: /etc/cont-init.d/15-keygen exited 0
cont-init: info: running /etc/cont-init.d/20-permissions
cont-init: info: /etc/cont-init.d/20-permissions exited 0
cont-init: info: running /etc/cont-init.d/50-config
User gid:    100
-------------------------------------

using keys found in /config/keys
cont-init: info: /etc/cont-init.d/50-config exited 0
cont-init: info: running /etc/cont-init.d/85-version-checks
[custom-init] no custom files found exiting...
[ls.io-init] done.
cont-init: info: /etc/cont-init.d/85-version-checks exited 0
cont-init: info: running /etc/cont-init.d/90-custom-folders
cont-init: info: /etc/cont-init.d/90-custom-folders exited 0
cont-init: info: running /etc/cont-init.d/99-custom-files
cont-init: info: /etc/cont-init.d/99-custom-files exited 0
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service init-mods: starting
s6-rc: info: service init-mods successfully started
s6-rc: info: service init-mods-package-install: starting
s6-rc: info: service init-mods-package-install successfully started
s6-rc: info: service init-mods-end: starting
s6-rc: info: service init-mods-end successfully started
s6-rc: info: service init-services: starting
s6-rc: info: service init-services successfully started
s6-rc: info: service legacy-services: starting
services-up: info: copying legacy longrun cron (no readiness notification)
services-up: info: copying legacy longrun nginx (no readiness notification)
services-up: info: copying legacy longrun php-fpm (no readiness notification)
s6-rc: info: service legacy-services successfully started
s6-rc: info: service 99-ci-service-check: starting
s6-rc: info: service 99-ci-service-check successfully started
```

**Comment by thespad** [comment]
This looks like an environmental issue rather than a problem with the image. External DNS lookups are failing which means either the container can't make them or the host can't.

**Comment by DennisYildirim** [comment]
Any tips and tricks to solve / diagnose ? I'm doing it on Synology DS1821+ which did not let me to connect exec -it via portainer. to run dnslookup from the inside of containers :(

**Comment by thespad** [comment]
We don't recommend or support Portainer for container management, but as long as the container is running nothing should stop you being able to exec in and run tests (although you may have the chicken/egg problem of no DNS in the container and no installed tools to diagnose the problem with).

I'm assuming that you can resolve external addresses OK from the NAS itself?
