### ISSUE TITLE
Set session.save_path for Azure/Cloud

### ISSUE THREAD

**Issue by kirbyAlasdairAnswer** [linuxserver/docker-grav#30]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

The grav admin platform experiences 'Invalid Token' errors on login when running in azure.
After many hours the problem was found to be that the token session.save_path was empty in etc/php81/php.ini.
The fix was to add the following to the dockerfile `session.save_path=\"/tmp\"" >> /etc/php81/php.ini`

### Reason for change

Setting this will allow anyone attempting to host this in the cloud to access the admin portal without issue

### Proposed code change

session.save_path=\"/tmp\"" >> /etc/php81/php.ini

**Comment by nemchik** [comment]
You should be able to add this line to `/config/php/php-local.ini` and restart your container. I don't think this change is something applicable to everyone. The grav documentation does not mention this setting either. I'm glad you were able to find how to fix the issue, and I would advise using the `php-local.ini` file as your permanent fix. If the grav documentation changes to include a specific recommendation for this setting we will consider adding it.

Also, note the warning https://www.php.net/manual/en/session.configuration.php#ini.session.save-path regarding using `/tmp`. It should be less applicable in the context of a docker image, but still worth noting.
