### ISSUE TITLE
Support for webp Plugin

### ISSUE THREAD

**Issue by JS-Media-Creation** [linuxserver/docker-grav#38]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

Hey there, is there a possibility to add support for the [webp Plugin](https://github.com/greenrivers/grav-plugin-webp)?

Requirements would be:

- install packages: libwebp-dev, webp
- enable GD and configure PHP to enable support for webp format

Thanks!

### Reason for change

The possibility to use the [webp Plugin](https://github.com/greenrivers/grav-plugin-webp) would be a big deal for more performance of GRAV sites.

**Comment by nemchik** [comment]
You might be able to achieve this with our docker mod
```yaml
- DOCKER_MODS=linuxserver/mods:universal-package-install
- INSTALL_PACKAGES=libwebp-dev|php82-gd
```

**Comment by JS-Media-Creation** [comment]
Thanks for your fast response! The packages installing fine, but the plugin still doesn't work :( Made the unit test and it outputs:

```Codeception PHP Testing Framework v4.2.2 https://helpukrainewin.org
Powered by PHPUnit 7.5.20 by Sebastian Bergmann and contributors.

Unit Tests (6) -------------------------------------------------------------------------------------------------------------------------------------
E ImageTest: Get image data (0.02s)
E ImageTest: Get image data from cli (0.00s)
✔ ImageTest: Get webp path (0.00s)
✔ ImageTest: Get webp dir (0.00s)
✔ ViewTest: Get jpg image extension (0.00s)
✔ ViewTest: Get webp image extension (0.00s)
----------------------------------------------------------------------------------------------------------------------------------------------------


Time: 203 ms, Memory: 4.00 MB

There were 2 errors:

---------
1) ImageTest: Get image data
 Test  tests/unit/Helper/ImageTest.php:testGetImageData
                                                                           
  [ParseError] syntax error, unexpected token "match", expecting variable  
                                                                           
#1  /config/www/user/plugins/webp/vendor/composer/ClassLoader.php:428
#2  /config/www/user/plugins/webp/tests/unit/Helper/ImageTest.php:37
#3  /config/www/user/plugins/webp/vendor/bin/codecept:117

---------
2) ImageTest: Get image data from cli
 Test  tests/unit/Helper/ImageTest.php:testGetImageDataFromCli
                                                                           
  [ParseError] syntax error, unexpected token "match", expecting variable  
                                                                           
#1  /config/www/user/plugins/webp/vendor/composer/ClassLoader.php:428
#2  /config/www/user/plugins/webp/tests/unit/Helper/ImageTest.php:63
#3  /config/www/user/plugins/webp/vendor/bin/codecept:117

ERRORS!
Tests: 6, Assertions: 4, Errors: 2.
```

But I think the problem is that the plugin might not supports php82. What do you think?

**Comment by nemchik** [comment]
> But I think the problem is that the plugin might not supports php82. What do you think?

That would be my first guess. You may want to open an issue on their repo and supply the above log and ask what they think. Feel free to link to this issue for reference. If there's a problem with the container or the packages or the nginx configurations it might be something that needs to be adjusted on our end.

**Comment by JS-Media-Creation** [comment]
> > But I think the problem is that the plugin might not supports php82. What do you think?
> 
> That would be my first guess. You may want to open an issue on their repo and supply the above log and ask what they think. Feel free to link to this issue for reference. If there's a problem with the container or the packages or the nginx configurations it might be something that needs to be adjusted on our end.

Yep, I just opened a issue on their repo: https://github.com/greenrivers/grav-plugin-webp/issues/9#issue-1846757615 and referenced this one here.

**Comment by nemchik** [comment]
Per https://github.com/greenrivers/grav-plugin-webp/issues/9#issuecomment-1684250107
It sounds like you might need to do 
```yaml
- DOCKER_MODS=linuxserver/mods:universal-package-install
- INSTALL_PACKAGES=libwebp-dev|php82-exif|php82-gd
```

**Comment by JS-Media-Creation** [comment]
@nemchik Perfect, that works! Thank you!
