### ISSUE TITLE
Adding Brotli compression in the embedded NGinx

### ISSUE THREAD

**Issue by Cl-Chris** [linuxserver/docker-grav#43]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

I see that the PHP Brotli is loaded in the docker, but is not activated in Nginx. May be it will be a good idea to use it to increase performance.
Also how to use Redis with this container ? Do we need a separate docker for Redis ?

### Reason for change

Increase performance.

### Proposed code change

Activate Brotli in the docker

**Comment by homerr** [comment]
Module has been added
