### ISSUE TITLE
[FEAT] add PHP extension pdo_sqlite

### ISSUE THREAD

**Issue by bigfreak85** [linuxserver/docker-grav#49]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

please add php extension pdo_sqlite to the container so that pagestats plugin https://github.com/francodacosta/grav-plugin-page-stats can be used.

### Reason for change

Compatibility with existing plugins

**Comment by aptalca** [comment]
In the meantime, you can use https://github.com/linuxserver/docker-mods/tree/universal-package-install

**Comment by bigfreak85** [comment]
Hi @aptalca  thanks for the hint! works with the following packages:
php-pdo_sqlite|php-pdo

**Comment by bigfreak85** [comment]
created #50 waiting for merge
