### ISSUE TITLE
How to Use Grav Skeleton's ?

### ISSUE THREAD

**Issue by drolfe** [linuxserver/docker-grav#7]
Hi, 

Is there anyway to use a Grav Skeleton with this template ?

Really I need the entire /app/grav-admin to be a persistence volume 

Any help would be great

Regards, Daniel

**Comment by Roxedus** [comment]
You dont need the whole /app folder. You can place the user folder from the theme/skeleton in /config/www/user, as thats whats different from the grav base

**Comment by drolfe** [comment]
> You dont need the whole /app folder. You can place the user folder from the theme/skeleton in /config/www/user, as thats whats different from the grav base

Thanks , that fixed my issue
